const DICTIONARY = {
    en: {
        PLAY_AGAIN_QUESTION: "Play again (YES/no)? ",
        CONFIRM: "y",
        MENU_TITLE: "MENU",
        START_GAME_PVP: "1. Play Game (PvP)",
        START_GAME_PVC: "2. Play Game (PvC)",
        SETTINGS: "3. Settings",
        EXIT_GAME: "4. Exit Game",
        SELECT_OPTION: "Select an option: ",
        INVALID_CHOICE: "Invalid choice. Please try again.",
        SETTINGS_TITLE: "Settings Menu",
        CHANGE_LANGUAGE: "1. Change Language",
        BACK_TO_MENU: "2. Back to Main Menu",
        CHOOSE_LANGUAGE: "Choose Language:",
        LANGUAGE_ENGLISH: "1. English",
        LANGUAGE_SERBIAN: "2. Serbian",
        PLACE_MARK: "Place your mark at (row col): ",
        PLAYER_TURN: "Player one it is your turn",
        WINNER: "Winner is Player ",
        DRAW: "The game is a draw!",
        GAME_OVER: "GAME OVER",
    },
    srb: {
        PLAY_AGAIN_QUESTION: "поново играти/Ponovo igrati (да/бр)? ",
        CONFIRM: "d",
        MENU_TITLE: "МЕНИ/Meni",
        START_GAME_PVP: "1. Играј (Играч против играча)",
        START_GAME_PVC: "2. Играј (Играч против рачунара)",
        SETTINGS: "3. Подешавања",
        EXIT_GAME: "4. Изађи",
        SELECT_OPTION: "Изаберите опцију: ",
        INVALID_CHOICE: "Неважећи избор. Покушајте поново.",
        SETTINGS_TITLE: "Подешавања/Podsetavanja",
        CHANGE_LANGUAGE: "1. Промени језик",
        BACK_TO_MENU: "2. Назад у мени",
        CHOOSE_LANGUAGE: "Изаберите језик:",
        LANGUAGE_ENGLISH: "1. Енглески/English",
        LANGUAGE_SERBIAN: "2. Српски/Serbian",
        PLACE_MARK: "Унесите свој потез (ред колона): ",
        PLAYER_TURN: "Играчу један је ваш ред",
        WINNER: "Победник је Играч ",
        DRAW: "Игра је нерешена!",
        GAME_OVER: "ИГРА ЈЕ ЗАВРШЕНА",
    }
};

export default DICTIONARY;
